// <auto-generated />
using System;
using AplikasiPemesananBus_UAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AplikasiPemesananBus_UAS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AplikasiPemesananBus_UAS.Models.BusModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Kapasitas")
                        .HasColumnType("integer");

                    b.Property<string>("NamaBus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorPlat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TarifBase")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("NomorPlat")
                        .IsUnique();

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("AplikasiPemesananBus_UAS.Models.PemesananModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BusID")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahTiket")
                        .HasColumnType("integer");

                    b.Property<int>("PemesananID")
                        .HasColumnType("integer");

                    b.Property<int>("PenumpangID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Retribusi")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TanggalPemesanan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TarifDasar")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalBayar")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("BusID");

                    b.HasIndex("PenumpangID");

                    b.ToTable("Pemesanan");
                });

            modelBuilder.Entity("AplikasiPemesananBus_UAS.Models.PenumpangModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorHP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("NomorHP")
                        .IsUnique();

                    b.ToTable("Penumpangs");
                });

            modelBuilder.Entity("AplikasiPemesananBus_UAS.Models.PemesananModel", b =>
                {
                    b.HasOne("AplikasiPemesananBus_UAS.Models.BusModel", "BusModel")
                        .WithMany("Pemesanan")
                        .HasForeignKey("BusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AplikasiPemesananBus_UAS.Models.PenumpangModel", "PenumpangModel")
                        .WithMany("Pemesanan")
                        .HasForeignKey("PenumpangID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusModel");

                    b.Navigation("PenumpangModel");
                });

            modelBuilder.Entity("AplikasiPemesananBus_UAS.Models.BusModel", b =>
                {
                    b.Navigation("Pemesanan");
                });

            modelBuilder.Entity("AplikasiPemesananBus_UAS.Models.PenumpangModel", b =>
                {
                    b.Navigation("Pemesanan");
                });
#pragma warning restore 612, 618
        }
    }
}
